name: ghost_kitchens_app
description: "Ghost Kitchen mobile app — Flutter + Clean Architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5

  cupertino_icons: ^1.0.8

  # === Networking ===
  dio: ^5.7.0

  # === Secure storage para tokens ===
  flutter_secure_storage: ^9.2.2

  # === Manejo de estado opcional ===
  provider: ^6.1.2

  # === JSON serialization (lo puedes usar más adelante) ===
  json_annotation: ^4.9.0

  shared_preferences: ^2.2.3

  google_maps_flutter: ^2.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Necesarios si luego quieres automatizar DTOs
  json_serializable: ^6.8.0
  build_runner: ^2.4.8

  # 👇 NUEVO: icono e splash nativo
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  # 👇 Activa tus assets donde está el logo
  assets:
    - lib/assets/images/

# 👇 Configuración del icono de la app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/logo.png"

# 👇 Configuración del splash nativo (pantalla que sale ANTES de tu SplashPage)
flutter_native_splash:
  color: "#000000"                     # puedes cambiar el color si quieres
  image: "lib/assets/images/logo.png"  # usamos tu mismo logo
  android: true
  ios: true
  android_gravity: center
