name: ghost_kitchens_app
description: "Ghost Kitchen mobile app — Flutter + Clean Architecture."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5

  cupertino_icons: ^1.0.8

  # === Networking ===
  dio: ^5.7.0

  # === Secure storage para tokens ===
  flutter_secure_storage: ^9.2.2

  # === Manejo de estado opcional ===
  provider: ^6.1.2

  # === JSON serialization (lo puedes usar más adelante) ===
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Necesarios si luego quieres automatizar DTOs
  json_serializable: ^6.8.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  # Activa esto cuando tengas assets
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Activa esto cuando agregues fuentes
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700


#google_maps_flutter: ^2.0.0  # o la versión estable más reciente
